### ISSUE TITLE
Linking from schedule to speaker abstracts is broken

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1065]
Probably worth fixing in #1010 what do you think @mxsasha ?

**Comment by plaindocs** [comment]
So, current template code expects a `Slug` in the schedule YAML:

Adding a column to the speaker spreadsheet to extract it *before* generating the schedule YAML looking something like  `=LOWER(SUBSTITUTE(TRIM(REGEXEXTRACT(B4,"[a-zA-Z ]+"))," ","-"))` works. 

There is probably a better way.

#1105 already contains the fix. 

Should probably go back and fix 

- [x] Prague 2019 #1106 
- [x] Portland 2019

**Comment by plaindocs** [comment]
Probably we should update `schedule-csv2yaml.sh` (aka csv.sh) and add the logic from `fix_slugs.py` to it, and then delete `fix_slugs.py`. 

@mxsasha what do you think?

**Comment by mxsasha** [comment]
Well, for 2020 this looks different - we don't use speaker slugs, we use talk slugs. I'll have a look at how the csv2yaml script handles that now, and get it updated for the 2020 format.

**Comment by plaindocs** [comment]
Sounds good! :-)

**Comment by mxsasha** [comment]
I can confirm the links between the schedule to specific speakers work for Portland 2020 in master.

However, schedule-csv2yaml confuses me. In my imagine our process is:
1. We select which speakers we want, and this ends up in a spreadsheet
2. "Somehow", this gets converted into the [sessions YAML](https://github.com/writethedocs/www/blob/refactoring-1010-2/docs/_data/portland-2020-sessions.yaml) (formerly the speakers YAML) with their abstract, names of all speakers, etc.
3. At some point, we create a schedule YAML (previously seen as separate day-1/day-2)

Step 3 is now easier, the [schedule YAML](https://github.com/writethedocs/www/blob/refactoring-1010-2/docs/_data/portland-2020-schedule.yaml) has been simplified a lot. As far as I can see, `schedule-csv2yaml` deals with generating this YAML file, from a spreadsheet. I don't understand why we would have that step instead of just writing the YAML file? So I don't understand why we would use that script at all.

Step 2 is also where all the slugs are finalised. From the schedule, references to talks are only made through slugs. There should be a single process of how to decide on the slug of a talk, happening in step 2, and then that slug needs to be placed in the schedule (videos may be weirder for a bit, but we'll fix that in the future).

So unless I'm misunderstanding something, both `fix-slugs` and `schedule-csv2yaml` are obsolete?

**Comment by plaindocs** [comment]
We export from Grorg to the spreadsheet, and futz to get all the YAMLs. Handwriting those YAML files is IMO an horrible idea.

New schedule YAML is awesome!

And we need the manual shuffling around in the spreadsheets to assemble the schedule.

* So we need some form of `schedule-2csv2yaml`.
* `fix-slugs` is probably obsolete, if the logic is built into the new video process.

**Comment by mxsasha** [comment]
I'm still confused. Writing the schedule YAML by hand doesn't seem any harder than writing the same data into Google spreadsheet? It's two lines of YAML per schedule slot.

The speakers/sessions YAML is a lot more work, so I expect we still use a script for that. But where is that script? That's not schedule-csv2yaml, right?

**Comment by mxsasha** [comment]
@plaindocs any thoughts on my last comment?

**Comment by plaindocs** [comment]
Oops, missed this.

I think writing the schedule YAML by hand from scratch is significantly more painful than adding speaker names into a spreadsheet that handles the times and sessions. But a YAML template with times would fix that I guess. 

I think extracting the initial session data from Grorg is still a dependency on @ericholscher which I'd love to avoid for the next conf.

**Comment by mxsasha** [comment]
I am still confused, but I also don't know what the actual input data is. There is some CSV that currently is used to generate the schedule, but what is in it? Because our new schedule YAML is literally two lines per schedule item: the time and either a talk slug or a plain-text title ("lunch"). (Speaker names and talk titles are no longer in the schedule.)

We can definitely support writing the schedule into a sheet, convert that to CSV, then convert that to JSON, but I just do not see how this has any benefit in terms of effort. Every slot in the schedule requires entering the time and the slug or plain-text title, whether that's in a sheet or in YAML.

**Comment by plaindocs** [comment]
I suspect we're talking around in circles here. Whatever we use produces the old schedule yaml not the new schedule, right? 

Whatever we export from Grorg, I'd like to get a list of slugs, and be able to paste those into an existing structure. Which as you point out, works as easily with YAML as with a spreadsheet.
