### ISSUE TITLE
Better jinja errors

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1829]
@ericholscher @mxsasha  Can we add a file and line number to these errors? 

```
Handler <function render_rst_with_jinja at 0x7f08a08b6b00> for event 'source-read' threw an exception (exception: 'unconf' is undefined)
```

**Comment by ericholscher** [comment]
Maybe. It's almost certainly coming from the `conf.py`, but guessing it's run in some undefined context.

**Comment by plaindocs** [comment]
Most likely to be in `load_conference_context_from_yaml` in `_ext/core.py` after @mxsasha 's refactor a while back?

**Comment by mxsasha** [comment]
Do you have an example of a build that failed on this? Then I can mess around with it and see if we can print more context. Looked through some recent failures but did not see this type.

**Comment by plaindocs** [comment]
I thought it was one of the recent broken ones in the Australia PR, but all I'm getting now is this

```
Handler <function render_rst_with_jinja at 0x7fc53fd82b00> for event 'source-read' threw an exception (exception: include/schedule2022.rst)
```

in 0908bf29

**Comment by mxsasha** [comment]
I can't reproduce that last one, as the branch is gone.

For the initial error about unconf being undefined: #1833. Line numbers are not available in the error.
The root cause here is that our YAML validator is quite flexible, to allow historical YAML files too. We could make a separate schema for newer files, or just make a stricter schema and only validate newer files, as the old ones don't really change.
